name: Build and Store Artifact

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.arch.os }}
    strategy:
      matrix:
        arch:
          - os: macos-13
            arch: x64
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make && mv nowplaying-cli nowplaying-cli-${{ matrix.arch.arch }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nowplaying-cli-${{ matrix.arch.arch }}
          path: nowplaying-cli-${{ matrix.arch.arch }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: nowplaying-cli-${{ matrix.arch.arch }}
          tag_name: latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
