name: Build and Store Artifact

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.arch.os }}
    strategy:
      matrix:
        arch:
          - os: macos-13
            arch: x64
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nowplaying-cli-${{ matrix.arch.arch }}
          path: ./nowplaying-cli
